### ISSUE TITLE
External drive access and additional plugins

### ISSUE THREAD

**Issue by acoolmanfromnowhere** [sdelrio/rpi-torrent-box#5]
I installed this on my Pi3B+ and it installed fine. I'm able to access rutorrent interface. The problem that I face is access the external drives. Whenever I try to add a torrent I get the error Failed to add torrent: Incorrect downloads directory was specified. I am able to access the external drive via SSH fine. It mounts at /media. I think it's a permission issue or something.

Second thing is how to install the additional plugins like filemanager.

Also while reboot Pi3, the external drives would take some time to mount, say around 5 seconds. Will this create a problem?

BTW, thanks for creating this. Very useful. Appreciate the effort. 👍

**Comment by sdelrio** [comment]
If your drive takes like 5 secs to mounts probably is because is on Idle state and it has to spin up. This is operative system issue, has nothing to do with this docker.

When you add the torrent it saves the .torrent file into the `.session`directory, but it should already have the correct privileges on first instart unles you copied from another rutorrent configuration. Check uid/gid is 33 (www-data). (In your case it should be something like /media/rutorrent/.session. Also check you have free space on your drive.

```
$ ls -lad /mnt/rutorrent/.session/
drwxr-xr-x 2 www-data www-data 36864 Aug  4 10:32 /mnt/rutorrent/.session/
$ ls -ladn /mnt/rutorrent/.session/
drwxr-xr-x 2 33 33 36864 Aug  4 10:32 /mnt/rutorrent/.session/
```

I won't recommend to install much more plugins since the Pi is a small cpu and low ram. You can `docker  exec -ti <yourdockerid> /bin/bash` and be inside of the docker and install the usuall way but if you destroy and create the docker you will have to redo again. So you can fork my repo, edit the docker file, add the instructions needed for that plugin and create your own docker image. What does filemanager plugin? since is a 3rd party plugin I don't think I would add to my repo because I want to keep it only the base installation. There is already some incompatibility issues when some lib is updated and don't want to create more problems when I need to upgrade versions.

About the mounting I use external drive and have no problems, I just use the noatime instead of defaults to reduce usage on that drive. Part of my `/etc/fstab`:

```
UUID=yourdrive_uuid_or_dev_sdx     /mnt            ext4    noatime   0       2
```
